### ISSUE TITLE
Send alert if IDChain related services are down

### ISSUE THREAD

**Issue by abramsymons** [BrightID/IDChain-Alert#2]
There are different services that IDChain users depend on those services:
1) rpc and ws services at https://idchain.one/rpc and wss://idchain.one/ws
2) blockscout service at https://explorer.idchain.one
3) aragon service at https://aragon.idchain.one
4) the claim service for Eidi at https://idchain.one/begin

The bot should monitor all of these services and send alerts if they went down.

**Comment by siftal** [comment]
https://github.com/IDChain-eth/IDChain-Alert/commit/4598491969509470c83c5b94ad85074ec0fe78f5
https://github.com/IDChain-eth/IDChain-Alert/commit/f63876ecd71283de596942345acae8fb1c74a275
